[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "requests>=2.32.3",
    "trafilatura>=2.0.0",
    "uvicorn>=0.34.0",
]
